import image from "../Images/gaming.jpg"
 const productModel = [
   {
     id: Math.random() * 1111111111,
     name: "Dell XPS",
     price: "1231 USD",
     image: image,
     category: "PCs",
     cart: false,
     wish: false,
   },
   {
     id: Math.random()*1111111111,
     name: "iPhone 12",
     price: "1000 USD",
     image: image,
     category: "phones",
     cart: false,
     wish: false,
   },
   {
     id: Math.random()*1111111111,
     name: "Play Station 5",
     image: image,
     price: "600 USD",
     category: "Gaming",
     cart: false,
     wish: false,
   },
   {
     id: Math.random()*1111111111,
     name: "VR Camera",
     image: image,
     price: "300 USD",
     category: "other",
     cart: false,
     wish: false,
   },
   {
     id: Math.random()*1111111111,
     name: "Magnetic Ligtbulb",
     image: image,
     price: "91 USD",
     category: "other",
     cart: false,
     wish: false,
   },
   {
     id: Math.random()*1111111111,
     name: "Lenovo",
     image: image,
     price: "1231 USD",
     category: "PCs",
     cart: false,
     wish: false,
   },
   {
     id: Math.random()*1111111111,
     name: "RTX",
     image: image,
     price: "131 USD",
     category: "Gaming",
     cart: false,
     wish: false,
   },
   {
     id: Math.random()*1111111111,
     name: "Vacuum cleaner",
     image: image,
     price: "1231 USD",
     category: "Home",
     cart: false,
     wish: false,
   },
 ];
export default productModel